language: R
sudo: false
cache: packages
r_packages:
  - testthat
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c2f4410ff7cb797ef8b5
    on_success: change
    on_failure: always
    on_start: never