language: R
sudo: false
cache: packages
r_packages:
  - testthat
notification:
  slack:
    secure: Gva9WQAXRipVlly51e56909lJzmy16ZGoqcgLUKR8n4YBQzt/QsmzpXZuJpd62lId42t2+vVqvLROFtsvoEcv0fxuXp0hO5SwmlB+/WGr7j2/6d+YGptXUmiHtYOxGXmHmVDg+iB/qw6tcz3ebcKh0As1LDHyNSaeX3xFR1+SFS8zRhfuoApO+2oC4rMSr9LYbw17Jbqvpgd6qig0xxc/rSaG01ATASsXZDqsSJsQ6PZrwmLigV+tZVtQlBiAhwtAMGam9KfD5DjVgtLssPXB2fzsiculfzzkyHCTf6OXq1OMpY1YhilYDPjbpaw40iaHpbeJf4M0kFILP0MAFjWaUt1mehDWSQNgJYkq8uOXctJ/RAAjr3ewI2DHjfV0Q7URDNXB6mn6YO8OWCWy73u65/VzJcJNxg3c4ffLQ2GKJ2pD5YpbxB9BOiTBxStwe+TFW0jct1mDG8t8rw4yM/h40csXAPMGIN+M+guoJ4NirMYV1UmMRRd+/7X3yDk0ADsA0l4f2JobVGFkHaCKlw9sOwa8UI5jeLk4FsZvcUkB/iXqK5el0M/0cv3K2DBeLxmaPFP1ZpchsFhs5yVsv1UqFh8dxWFb9b5sQGEJBT1M31m8IR9R+TToOClBuVSNb+Px7cdjl2Ao4sEhkws7FPOX6qMHt7qU/EbPGWztzTiJyw=
